# Generated by Django 5.0.6 on 2024-08-05 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='doctors.city'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialty', to='doctors.specialty'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.medicalhistory'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty', 'city'], name='authenticat_special_39af76_idx'),
        ),
    ]
