# Generated by Django 5.0.6 on 2024-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['stars'], 'verbose_name': 'doctor', 'verbose_name_plural': 'doctors'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
    ]
