# Generated by Django 5.0.6 on 2024-08-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_doctor_options_doctor_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-stars'], 'verbose_name': 'doctor', 'verbose_name_plural': 'doctors'},
        ),
    ]
