# Generated by Django 5.0.6 on 2024-09-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_doctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pending'), ('Confirmada', 'Confirmed'), ('En progreso', 'In Progress'), ('Cancelada', 'Canceled'), ('Finalizada', 'Finished')], default='Pendiente', max_length=20),
        ),
    ]
