# Generated by Django 5.0.6 on 2024-09-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_doctor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pending'), ('Confirmado', 'Confirmed'), ('Cancelado', 'Canceled')], default='Pendiente', max_length=20),
        ),
    ]
