# Generated by Django 5.0.6 on 2024-08-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pending'), ('Confirmada', 'Confirmed'), ('En progreso', 'In Progress'), ('Cancelada', 'Canceled'), ('Finalizada', 'Finished')], max_length=20)),
                ('patient_appointment', models.DateTimeField()),
                ('start_appointment', models.DateTimeField()),
                ('end_appointment', models.DateTimeField()),
                ('accepted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient')),
            ],
            options={
                'verbose_name': 'Medical Appointment',
                'verbose_name_plural': 'Medical Appointments',
                'ordering': ['start_appointment'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_consultation', models.TextField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('medications', models.TextField()),
                ('treatment', models.TextField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_information', to='doctors.medicalappointment')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='medical_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.doctor')),
                ('medical_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.medicalappointment')),
            ],
            options={
                'verbose_name': 'Medical Attachment',
                'verbose_name_plural': 'Medical Attachments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['doctor'],
            },
        ),
    ]
