# Generated by Django 5.0.6 on 2024-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentinformation',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointmentinformation',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointmentinformation',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointmentinformation',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointmentinformation',
            name='treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='accepted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='end_appointment',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='start_appointment',
            field=models.DateTimeField(blank=True),
        ),
    ]
