# Generated by Django 5.0.6 on 2024-08-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_appointmentinformation_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='guid',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
