# Generated by Django 5.0.6 on 2024-08-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_medicalappointment_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentinformation',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentinformation',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentinformation',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentinformation',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentinformation',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='end_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='start_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pending'), ('Confirmada', 'Confirmed'), ('En progreso', 'In Progress'), ('Cancelada', 'Canceled'), ('Finalizada', 'Finished')], default='Pendiente', max_length=20),
        ),
    ]
