# Generated by Django 5.0.6 on 2024-08-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_doctor_options'),
        ('doctors', '0004_alter_appointmentinformation_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.patient'),
        ),
    ]
