# Generated by Django 5.0.6 on 2024-08-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_doctor_options'),
        ('doctors', '0005_alter_medicalappointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.doctor'),
        ),
    ]
