# Generated by Django 5.0.6 on 2024-09-16 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_medicalappointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentinformation',
            name='medical_appointment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_information', to='doctors.medicalappointment'),
        ),
    ]
